### PR TITLE
Implement Trust Region Method in SLP

### PR DESCRIPTION
**Pull request by ssadat**
Implementing the Trust Region Method in SLP to reproduce the TR paper for ACOPF paper

### CODE REVIEW

**Comment by ssadat** [comment]
Test results for `Line Search Algorithm`

**Comment by ssadat** [comment]
Test results for `Trust Region Algorithm`
```
Test Summary:                                            | Pass  Fail  Error  Total
MathOptInterface                                         |  422    55     21    498
  SolverName                                             |    1                   1
  supports_default_copy_to                               |    2                   2
  Unit                                                   |   48     8      7     63
    solve_qcp_edge_cases                                 |   12     2            14
      Duplicate on-diagonal                              |    7                   7
      Duplicate off-diagonal                             |    5     2             7
    add_variable                                         |    3                   3
    solve_duplicate_terms_vector_affine                  |    3     3             6
    solve_single_variable_dual_max                       |                    No tests
    solve_single_variable_dual_min                       |                    No tests
    solver_name                                          |    1                   1
    solve_time                                           |    1            1      2
    solve_duplicate_terms_obj                            |    2            1      3
    raw_status_string                                    |    1            1      2
    add_variables                                        |    3                   3
    feasibility_sense                                    |    3                   3
    max_sense                                            |    3                   3
    silent                                               |    4                   4
    min_sense                                            |    3                   3
    solve_duplicate_terms_scalar_affine                  |    3     3             6
    time_limit_sec                                       |    4                   4
    solve_qp_edge_cases                                  |    2            4      6
      Basic model                                        |                 1      1
      Duplicate linear terms                             |                 1      1
      Duplicate diagonal terms                           |                 1      1
      Duplicate off-diagonal terms                       |                 1      1
  MOI Linear tests                                       |  244    37      7    288
    linear14                                             |   18    11            29
    linear6                                              |   20            1     21
    linear4                                              |    9            1     10
    linear3                                              |   12            1     13
    linear9                                              |   12     3            15
    linear1                                              |   83    12            95
    linear2                                              |   16     3            19
    partial_start                                        |    6                   6
    linear10b                                            |   13                  13
    linear10                                             |   13            1     14
    linear5                                              |   20     8            28
    linear13                                             |    6            1      7
    linear11                                             |    7            1      8
  MOI QP tests                                           |   14     4            18
    qp3                                                  |   14     4            18
  MOI QCQP tests                                         |   48     6      2     56
    qcp3                                                 |    9            1     10
    qcp4                                                 |   15     3            18
    qcp5                                                 |   15     3            18
    qcp2                                                 |    9            1     10
  MOI NLP tests                                          |   20            5     25
    feasibility_sense_with_objective_and_hessian         |    4            1      5
    feasibility_sense_with_no_objective_and_no_hessian   |    4            1      5
    feasibility_sense_with_objective_and_no_hessian      |    4            1      5
    feasibility_sense_with_no_objective_and_with_hessian |    4            1      5
    nlp_objective_and_moi_objective                      |    4            1      5
  Testing getters                                        |   37                  37
  Bounds set twice                                       |    8                   8
ERROR: LoadError: Some tests did not pass: 422 passed, 55 failed, 21 errored, 0 broken.

```

**Comment by ssadat** [comment]
By commenting line `94` to `98` in `SLP_line_search.jl`, the `Line Search Algorithm` passes all the tests, with the test results shown below:
```
Test Summary:    | Pass  Total
MathOptInterface |  636    636
```
```
Test Summary:  | Pass  Total
toy_example.jl |    2      2
```
```
Test Summary: |
opf.jl        | No tests
Test.DefaultTestSet("opf.jl", Any[], 0, false)
```

**Comment by kibaekkim** [comment]
This PR should wait until the trust region is done. I will create a separate PR for #84.

**Pull request closed without merging**
