### PR TITLE
Improving SLP algorithm performance

### LINKED ISSUE #111: Improve Jacobian Calculation
The Jacobian calculation is implemented inefficiently and, therefore, very costly.

### LINKED ISSUE #112: KT residual has performance issues

### LINKED ISSUE #113: Constraint setup in LP subproblem is very costly

### LINKED ISSUE #114: Error Tolerance for LP Solver Coefficient Ranges
Add a `tol_error` in `parameters.jl` to define the LP coefficient ranges

### LINKED ISSUE #117: PR #116 Error (some solvers doesn't support number of simplex iterations)

### LINKED ISSUE #118: Unconstrained problems results in errors
For unconstrained problems, the code results in errors in a couple of places. This is because the number of variables is calculated from the `size(qp.A)`, resulting in errors when we don't have any constraints.

### LINKED ISSUE #119: Add termination to SLP when LP subproblem is infeasible
The algorithm doesn't terminate when the LP subproblem is infeasible. A proper termination should be added when the `PrimalStatus` of the LP subproblem is not `FEASILBE_POINT`.

### PR DESCRIPTION
**Pull request by sasadat**
There are a few performance bottlenecks in the SLP algorithm's implementations that need to be revised and efficiently reimplemented.

### CODE REVIEW

**Review by kibaekkim — CHANGES_REQUESTED** [review]
Please request the review again once the conflicts are resolved.

**Review by sasadat — COMMENTED** [review]
The PR is ready to be closed

**Comment by kibaekkim** [comment]
Just to make sure, does not this PR need merged? Just close?

**Review by sasadat — COMMENTED** [review]
I meant ready to merge. I will open another PR for fixing the Trust Region method

**Comment by kibaekkim** [comment]
Now it is hard to see what has been added/deleted/modified from `master` to `ssadat_new` repos. Can you try to merge `master` to your repo and see if "Files changed" shows the differences correctly?

**Pull request closed without merging**
